calcRSA/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import url

from . import views
app_name = 'calcRSA'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

course/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls import url, include

from . import views

app_name = 'course'
urlpatterns = [
    # ex: /course/
    url(r'^$', views.index, name='index'),
    # ex: /course/5/
    url(r'^(?P<course_id>[0-9]+)/$', views.detail_course, name='detail_course'),
    url(r'^(?P<course_id>[0-9]+)/(?P<task_id>[0-9]+)/', views.task, name='task'),
    #url(r'^(?P<course_id>[0-9]+)/test/', include('test_task.urls', namespace="test_task")),
]

cryptocours/urls.py
# -*- coding: UTF-8 -*-
"""cryptocourse URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from cryptocours import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^course/', include('course.urls')),
    url(r'^user/', include('user_profile.urls')),
    url(r'^test/', include('test_task.urls')),
    url(r'^rsa/', include('calcRSA.urls')),
    url(r'^sdes/', include('sdes.urls')),
    url(r'^admin/', admin.site.urls),
    
]

sdes/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls import url, include

from . import views

app_name = 'sdes'
urlpatterns = [
    # ex: /course/
    url(r'^$', views.index, name='index'),
    ]

test_task/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls import url

from . import views

app_name = 'test_task'
urlpatterns = [
    # ex: /tests/
    url(r'^(?P<course_id>[0-9]+)/(?P<test_task_id>[0-9]+)/', views.index, name='index'),
    # ex: /course/5/
]

user_profile/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import patterns, include, url

from . import views

app_name = 'user_profile'
urlpatterns = [
    # ex: /course/
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^login/$', views.login_view, name='login_view'),
    url(r'^logout/$', views.logout_view, name='logout_view'),
]

course/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User



# Модель Курс    
class Course(models.Model):
    course_name = models.CharField("Название", max_length=200)
    image = models.ImageField("Изображение", upload_to='course/static/images')
    details = models.TextField("Описание")
    class Meta:
        db_table = 'course'
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'
        #ordering = ['-created_at']

    def __unicode__(self):
        return self.course_name

# Модель Задание    
class Task(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.TextField()
    theory = models.TextField()
    task = models.TextField()
    answer_task = models.CharField(max_length=50)
    
    class Meta:
        db_table = 'task'
        verbose_name = 'Задание'
        verbose_name_plural = 'Задания'
        #ordering = ['-created_at']

    def __unicode__(self):
        return self.title

# Модель Пройденное задание
class Attempts_task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    date_task = models.DateTimeField('date task')
    
    class Meta:
        db_table = 'attempts_task'
        verbose_name = 'Пройденное задание'
        verbose_name_plural = 'Пройденные задания'
        #ordering = ['-created_at']

    def __unicode__(self):
        return unicode(self.user)

course/views.py
# -*- coding: UTF-8 -*-

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.core.context_processors import csrf
from django.shortcuts import redirect
from django.contrib import auth
from django.utils import timezone
from .models import *
import test_task


#  Страница КУРСЫ
def index(request):
    if request.user.is_authenticated():
        latest_course_list = Course.objects.all()
        for c in range(len(latest_course_list)):
            latest_course_list[c].image_url = "/static/images/"+latest_course_list[c].image.url.split('/')[-1]
        context = {'latest_course_list': latest_course_list}
        return render(request, 'course/course.html', context)
    else:
        return redirect("user_profile:login_view")
   
# Список заданий    
def detail_course(request, course_id):
    if request.user.is_authenticated():
        course = Course.objects.get(id = course_id)
        task_list = Task.objects.filter(course = course_id)
        test_list = test_task.models.Test_task.objects.filter(course = course_id)
        context = {'course':course,'task_list': task_list, 'test_list':test_list}
        return render(request, 'course/detail_course.html', context)
    else:
        return redirect("user_profile:login_view")   
  
# Задание
def task(request, course_id, task_id):
    if request.user.is_authenticated():
        task = Task.objects.filter(course = course_id)[int(task_id)-1:int(task_id)+1]
        next_task = Task.objects.filter(course = course_id)[int(task_id):int(task_id)+2]
        
        if request.method == "POST" and request.is_ajax():
            inputtask = request.POST.get('inputtask', '')
            if task[0].answer_task == inputtask:
                data = { 'date_task' : timezone.now()}
            #сохранение выполненого задания
                attempts_task = Attempts_task.objects.update_or_create(user = request.user, task = task[0], defaults = data)
                print("ok")
                return HttpResponse("ok")
            else:
                print("not ok")
                return HttpResponse("not ok")
        else:
            if next_task:
                context = {'task': task[0], 'course_id': course_id, 'task_id':task_id, 'next_task': int(task_id)+1}
            else:
                context = {'task': task[0], 'course_id': course_id, 'task_id':task_id, 'test_id': 1 }
            return render(request, 'course/task.html', context)
    else:
        return redirect("user_profile:login_view")
        

course/templates/course/course.html
{% extends "course/index.html" %}
{% block content %}
<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="{% url 'course:index' %}">Главная</a></li>
			<li class="active">Курсы</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-sm-9 maincontent">
				<header class="page-header">
					<h2 class="page-title">Список курсов</h2>
					<p>Доступные курсы: </p>
					<!-- button -->
				</header>
				
				<!-- Intro -->
            	<div class="container text-left">
            		<div class="row">
                        {% if latest_course_list %}
                            {% for course in latest_course_list %}
                            <div class="course">
                                <img class="bord" src="{{ course.image_url }}"> 
                                <div>
                                <a href="{% url 'course:detail_course' course.id %}">{{ course.course_name }}</a>
                                <p> {{ course.details }}</p>	
                                </div>
                            </div><br>
                            {% endfor %}
                        {% else %}
                            <p>К сожалению, пока что нет доступных курсов. </p>
                        {% endif %}
                    </div>
        		</div>
				
			</article>
			<!-- /Article -->
	</div>	
</div>



{% endblock %}

course/templates/course/detail_course.html
{% extends "course/index.html" %}

{% block content %}
<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="{% url 'index' %}">Главная</a></li>
			<li><a href="{% url 'course:index' %}">Курсы</a></li>
			<li class="active">Задания</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-sm-12 maincontent">
				<header class="page-header">
					<h2 class="page-title">{{course.course_name}}</h2>
					<p>Доступные задания:</p>
					<!-- button -->
				</header>
				
				<!-- Intro -->
            	<div class="container text-left">
            		<div class="row">
            		    <div class="col-sm-7" id="task2">
                        {% if task_list %}
                            {% for task in task_list %}
                            
                                <div class="grey_div" style="margin:5px;">
                                <i class="fa fa-cogs  fa-2x" id="ico"></i>&nbsp; <a href="{% url 'course:task' course.id forloop.counter %}"> {{ task.title }}</a>
                                </div>
                            {% endfor %}
                        {% endif %}
                        
                        {% if test_list %}
                            {% for test in test_list %}
                                <div class="grey_div" style="margin:5px;">
                                <i class="fa fa-list-ol fa-2x" id="ico"></i>&nbsp; <a href="{% url 'test_task:index' course.id forloop.counter %}"> Тест. {{ test.name_test }}</a>
                                </div>
                            {% endfor %}
                        {% endif %}
                        </div>
                        <div class="col-sm-4 course_details"> {{course.details}}</div>
                    </div>
        		</div>
				
			</article>
			<!-- /Article -->
	</div>	
</div>  

{% endblock %}

course/templates/course/home.html
{% extends "course/index.html" %}
{% block content %}
<!-- Header -->
	<header id="head">
		<div class="container">
			<div class="row">
				<h1 class="lead">CryptoCourse</h1>
				<p class="tagline"> Онлайн-курсы по криптографии и шифрованию</p>
				{% if request.user.is_authenticated %}
				<p> <a href="{% url 'course:index' %}" class="btn btn-action btn-lg" role="button">НАЧАТЬ</a></p>
				{% else %}
				<p> <a href="{% url 'user_profile:login_view' %}" class="btn btn-action btn-lg" role="button">НАЧАТЬ</a></p>
				{% endif %}
			</div>
		</div>
	</header>
	<!-- /Header -->

	<!-- Intro -->
	<div class="container text-center">
		<br> <br>
		<h2 class="thin">Лучший способ выучить криптографию</h2>
		<p class="text-muted">
			Мы создали для Вас самый подробный интерактивный курс о методах шифрования.<br> Более 100 заданий помогут Вам освоить криптографию без труда.
		</p>
	</div>
	<!-- /Intro-->
		
	<!-- Highlights - jumbotron -->
	<div class="jumbotron top-space">
		<div class="container">
			
			<h3 class="text-center thin">Причины использовать CryptoCourse</h3>
			
			<div class="row">
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-book  fa-5"></i>Всё в одном </h4></div>
					<div class="h-body text-center">
						<p>На сайте собран теоретический материал по всем осповным методам шифрования.
						Вам больше не придется искать информацию на разных ресурсах. Просто выберете интересующий Вас курс.</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-key fa-5"></i>Практика</h4></div>
					<div class="h-body text-center">
						<p> В каждом курсе содержатся бесплатные интерактивные задания, 
						проходя которые вы сможете понять суть криптографических методов, а так же научитеть применять их на практике.  </p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-check-square-o fa-5"></i>Повторение</h4></div>
					<div class="h-body text-center">
						<p>После того как вы выполните все задания, вы сможете пройти тест. 
						Он помежет Вам определить насколько хорошо Вы освоии теоретический и практический материал.
						Если результат Вас не устроит, пройдтите курс снова!</p>
					</div>
				</div>
				<div class="col-md-3 col-sm-6 highlight">
					<div class="h-caption"><h4><i class="fa fa-bar-chart-o fa-5"></i>Результаты</h4></div>
					<div class="h-body text-center">
						<p> Вы всегда можете посмотреть насколько плодотворным было ваше обучение. 
						На личной странице пользователя Вы найдете оценки за пройденные тесты и количество выпоненных заданий в виде инфографики.</p>
					</div>
				</div>
			</div> 
		
		</div>
	</div>
	<!-- /Highlights -->

	<!-- container -->
	<div class="container">

		<div class="jumbotron top-space">
			<h4><em>« Каждый день, в который вы не пополнили своего образования хотя бы маленьким, но новым для вас куском знания... 
			считайте бесплодно и невозвратно для себя погибшим. »</em></h4>
     		<p class="text-right"><em>Константин Сергеевич Станиславский</em></p>
  		</div>

</div>	<!-- /container -->
{% endblock %}

course/templates/course/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author"      content="Anastasiya Ivanilova">
	
	<title>CryptoCourse</title>

	<!-- сделать иконку -->
	<link rel="shortcut icon" href="../static/images/key-tool.png">
	
	<link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="/static/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/css/font-awesome.min.css">

	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="/static/css/bootstrap-theme.css" media="screen" >
	<link rel="stylesheet" href="/static/css/main.css">
	<link rel="stylesheet" href="/static/css/task.css">
	
</head>

<body class="home">
	<script>
        window.urls = {
           'signin_success': '{% url "course:index" %}'
                
        };
    </script>
    <div>
    	<!-- Fixed navbar -->
    	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
    		<div class="container">
    			<div class="navbar-header">
    				<!-- Button for smallest screens -->
    				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
    				<a class="navbar-brand" href="{% url 'index' %}"><img src="/static/images/logo.png" alt="Progressus HTML5 template"></a>
    			</div>
    			
    			<div class="navbar-collapse collapse">
    				<ul class="nav navbar-nav pull-right">
    					<li><a href="{% url 'course:index' %}">Курсы</a></li>
    					<li class="dropdown">
    						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Калькулятор <b class="caret"></b></a>
    						<ul class="dropdown-menu">
    							<li class="active"><a href="{% url 'calcRSA:index' %}"> RSA </a></li>
    							<li class="active"><a href="{% url 'sdes:index' %}"> S-DES</a></li>
    						</ul>
    					</li>
    					{% if request.user.is_authenticated %}
    					<li><a href="{% url 'user_profile:index' %}"> {{ request.user.username }} </a></li>
    						<li><a class="btn" href="{% url 'user_profile:logout_view' %}"> Выход </a></li>
    					{% else %}
    						<li><a class="btn" href="{% url 'user_profile:register' %}"> Регистрация / Вход</a></li>
    					{% endif %}
    				</ul>
    			</div><!--/.nav-collapse -->
    			
    		</div>
    	</div> 
    	<!-- /.navbar -->
        {% block content %}
        
        
        {% endblock %}
    	
    	<footer id="footer" class="top-space">
    
    		<div class="footer1">
    			<div class="container">
    				<div class="row">
    					
    					<div class="col-md-3 widget">
    						<h3 class="widget-title">Контакты</h3>
    						<div class="widget-body">
    							<p>	<a href="mailto:#">Lumiera@meta.ua</a><br>
    								<br>
    								
    							</p>	
    						</div>
    					</div>
    
    					<div class="col-md-3 widget">
    						<h3 class="widget-title">Follow me</h3>
    						<div class="widget-body">
    							<p class="follow-me-icons">
    								<a href="https://vk.com/lumiera"><i class="fa fa-vk fa-2"></i></a>
    								<a href="https://www.instagram.com/lumiera_meow/"><i class="fa fa-instagram fa-2"></i></a>
    								<a href="https://github.com/LumieraMeow"><i class="fa fa-github fa-2"></i></a>
    								<a href="https://www.facebook.com/LumieraMeow"><i class="fa fa-facebook fa-2"></i></a>
    							</p>	
    						</div>
    					</div>
    
    					<div class="col-md-6 widget">
    						<h3 class="widget-title">О ресурсе</h3>
    						<div class="widget-body">
    							<p>Данный ресурс был создан с целью помочь всем желающим изучить основы криптографии и шиврования. 
    							Свои советы и предложения о том, как сделать программу обучения лучше, пожалуйста, пишите мне на почту. 
    							</p>
    							<p>Сделано для Вас с <span style="color: #e74c3c;">❤</span>.</p>
    						</div>
    					</div>
    
    				</div> <!-- /row of widgets -->
    			</div>
    		</div>
    
    		<div class="footer2">
    			<div class="container">
    				<div class="row">
    					
    					<div class="col-md-6 widget">
    						
    					</div>
    
    					<div class="col-md-6 widget">
    						<div class="widget-body">
    							<p class="text-right">
    								Copyright &copy; 2017, Иванилова Анастасия. 
    							</p>
    						</div>
    					</div>
    
    				</div> <!-- /row of widgets -->
    			</div>
    		</div>
    
    	</footer>	
    		
    
    
    
    
    	<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
    	
    	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    	<script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    	<script src="/static/js/jQuery.headroom.min.js"></script>
    	<script src="/static/js/jquery.submitForm.js"></script>
    	<script src="/static/js/headroom.min.js"></script>
    	<script src="/static/js/template.js"></script>
    	
</body>
</html>

course/templates/course/task.html
{% extends "course/index.html" %}

{% block content %}
<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container-fluid">

		<ol class="breadcrumb">
			<li><a href="{% url 'index' %}">Главная</a></li>
			<li><a href="{% url 'course:index' %}">Курсы</a></li>
			<li><a href="{% url 'course:detail_course' course_id %}">Задания</a></li>
			<li class="active">{{task.title}}</li>
		</ol>
			
				
		<!-- Intro -->
   		<div class="row cont">
   		    {% if task %}
   		    	
   		    	<div class="col-sm-6 task-block">
   		    		<div class="task">
   		    			<h3>Задание</h3>
   		    			<p>{{task.task|linebreaksbr}}</p>
   		    		</div>
					<form action="{% url 'course:task' course_id task_id %}" method="post" id="task">
						{% csrf_token %}
   		    			<input class="input-task" name="inputtask" type="text" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false">
   		    			{% if next_task %}
		   		   		<center><a href="{% url 'course:task' course_id next_task %}"  id="button-task" type="button" class="btn btn-warning disabled">Далее</a></center>
						{% else %}
						<center><a href="{% url 'test_task:index' course_id test_id %}"  id="button-task" type="button" class="btn btn-warning disabled">Далее</a></center>
		   		   		{% endif %}
		   		    </form>
   				</div>
   				<div class="col-sm-5 theory "> 
	   				<h3>Теория</h3>
	   				<p>{{task.theory|linebreaksbr}}</p>
   				</div>

            {% else %}
                <p>No course are available.</p>
            {% endif %}
        </div>
    </div>
				
{% endblock %}